baseurl = "https://lin2code.github.io/"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "林二狗的博客"
theme = "hugo-theme-dream"
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'
googleAnalytics = "UA-177179527-1"
disqusShortname = "lin2code"

# enableRobotsTXT = true
hasCJKLanguage = true

[params]
  #background = "black"
  backgroundImage = "/img/background.jpg"
  linkColor = "seagreen"

  author = "林二狗"
  description = "林二狗的笔记本"
  avatar = "/img/avatar.jpg"
  motto = "生死看淡 不服就干 活"

  #rss = true
  #utterancesRepo = ""
  
  github = "https://github.com/lin2code"
  email = "631320085@163.com"
  twitter = "https://twitter.com/yourlostpapa"
  instagram = "https://www.instagram.com/0xfade2018/"
  stackoverflow = "https://stackoverflow.com/users/12997179/lin2code"
  # facebook = ""
  # linkedin = ""
  # codepen = ""

  siteStartYear = 2020

  favicon = "/favicon.ico"

  # options
  showSummaryCoverInPost = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true
