baseurl = "https://lin2code.github.io/"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "林二狗"
theme = "hugo-theme-dream"
copyright = '本作品采用<a target="_blank" rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'
# googleAnalytics = "UA-177179527-1"
disqusShortname = "lin2code"

# enableRobotsTXT = true
hasCJKLanguage = true

[params]
  #background = "black"
  backgroundImage = "https://blog-lin2code-1252382346.file.myqcloud.com/background.jpg"
  linkColor = "#2185d0"

  author = "林二狗"
  description = "林二狗的笔记本"
  avatar = "https://blog-lin2code-1252382346.file.myqcloud.com/avatar.jpg"
  motto = "一个小码仔"

  #rss = true
  #utterancesRepo = ""
  
  github = "lin2code"
  email = "631320085@163.com"
  # twitter = "yourlostpapa"
  instagram = "0xfade2018"
  stackoverflow = "12997179"
  # facebook = ""
  # linkedin = ""
  # codepen = ""

  siteStartYear = 2020

  favicon = "/favicon.ico"

  # options
  showSummaryCoverInPost = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true
